name = "Mongeese Reborn Server"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ae57683e7482c7e801f213681c56e871c9197b1058a256d980ad009de49b651"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
