name = "Mongeese Reborn Server"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ce5bd1a0bb0353e986a8927b8c895fec4d42620e1539ced967b33246f44c82"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
