name = "Mongeese Reborn Server"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "196333b27689d1f78bf7c129f23da342ea24e71ff81c6222b2eacd565a5bedef"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
