name = "Mongeese Reborn Server"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e9e7fb9acdf08238ad607a848f52a6b3f468faea8d802125fe76e0dd7d7f8d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
