name = "Mongeese Reborn Plus"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63df4cf9656f4a19bf40fa4635f6636954aea8d5ba85cd1c16148a6b34258eeb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
