name = "Mongeese Reborn 2 Plus"
author = "Solomon Killam"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f563be2e952be55fa3bcacc43e60c5564aebe5913dc263eeac158ea8f166310e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
