name = "Mongeese Reborn"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "645b2a22aef202b670febdefc0d982e380ac9aeb45d93c66bbb00decdd8fbd40"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
