name = "Mongeese Reborn"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f17b388aa277c719f5b83ac285a5ccf7f646ebbf3153e31e97b5267bfcd34b82"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
