name = "Mongeese Reborn 2"
author = "Solomon Killam"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2acb2a9c785f662bc16ce16f0014509493e39cab7d6bf643c4da3802897b51fb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
